const projectImages = [
  "/images/projects/agarthaProject.png",
  "/images/projects/backlistProject.png",
  "/images/projects/cinocharProject.png",
  "/images/projects/coffeeTimeProject.png",
  "/images/projects/linkedinProject.png",
  "/images/projects/mvcArchitectureProject.png",
  "/images/projects/netflixProject.png",
  "/images/projects/osportProject.png",
  "/images/projects/restApiTournamentProject.png",
  "/images/projects/soloDevSaasTemplateProject.png",
  "/images/projects/soundyProject.png",
  "/images/projects/sqlShowcaseProject.png",
  "/images/projects/guild_simulator.png",
];

export const [
  agarthaProject,
  BacklistProject,
  cinocharProject,
  coffeeTimeProject,
  LinkedinProject,
  mvcArchitectureProject,
  NetflixProject,
  osportProject,
  restApiTournamentProject,
  soloDevSaasTemplateProject,
  soundyProject,
  SqlShowcaseProject,
  guild_simulator,
] = projectImages;
